name: 'Compile and publish all LaTeX'
description: 'Checkout, compile LaTeX, compute a version, and deploy on GitHub in one shot.'
inputs:
  token:  # github token
    description: 'Github token for deployment.'
    required: true
  publish-enable:
    description: 'Whether the results should be deployed on GitHub. Defaults to true.'
    required: false
    default: true
  overwrite-release:
    description: 'Whether the results should overwrite previous release. Defaults to true.'
    required: false
    default: true
  texfilter: 
    description: 'Filter for LaTex files'
    required: false
    default: ''
  limit:
    description: 'Limit LaTeX files to build to a number N'
    required: false
    default: 20
  latex_packages_to_install:
    description: 'A comma-separated list of LaTex packages to install'
    required: false
    default: 'beamer'

runs:
  using: "composite"
  steps:
    #- name: Make ImageMagik permissive
    #  shell: bash
    #  run: sudo sed -i 's/rights=".*"/rights="all"/' /etc/ImageMagick-6/policy.xml
    # Checkout the repository
    - name: Checkout
      uses: danysk/action-checkout@0.2.5
#    - name: Install hub
#      uses: geertvdc/setup-hub@master
    - name: run hub commands
      shell: bash 
      run: |
        export TAG="$(git describe --tags --always --abbrev=0 HEAD)" 
        echo -e "github.com:\n- user: $GITHUB_USER\n  oauth_token: $GITHUB_TOKEN\n  protocol: https" > $HOME/.config/hub
        gh release view $TAG # --format "%pr"
        # for only filenames: | sed -e 's/.*\///g'
        git log --since="$(gh release view $TAG)" --name-only --pretty=format: | sort | uniq | grep -e '.*\.tex' | tr '\n' ',' | sed -rn "s/(.*),/\1/p"
        export TEXFILTER=$(git log --since="$(gh release view $TAG)" --name-only --pretty=format: | sort | uniq | grep -e '.*\.tex' | tr '\n' ',' | sed -rn "s/(.*),/\1/p")
        if [[ "${{ inputs.texfilter }}" ]]; then
          export TEXFILTER="${{ inputs.texfilter }}"
        fi
        echo "TEXFILTER=$(echo $TEXFILTER)" 
        echo "TEXFILTER=$(echo $TEXFILTER)" >> $GITHUB_ENV
    - name: Compile LaTeX
      uses: metaphori/compile-latex-action@master
      with:
        texfilter: ${{ env.TEXFILTER }}
        limit: ${{ inputs.limit }}
        latex_packages_to_install: ${{ inputs.latex_packages_to_install }}
    #- name: Autotag
    #  uses: DanySK/semver-autotag-action@0.1.0
    #  if: inputs.overwrite-release == 'false'
    - name: Deploy
      if: inputs.publish-enable == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [[ -z $GITHUB_TOKEN ]]; then
          echo "No token set, cannot deploy"
          false
        else
          if [[ $GITHUB_REF == 'refs/heads/master'
              || $GITHUB_REF == 'refs/heads/main'
              || $GITHUB_REF == 'refs/heads/default'
              || $GITHUB_REF == "refs/tags"*
          ]]; then
            TAG="$(git describe --tags --abbrev=0 HEAD)"
            gh release edit "$TAG" --notes "$(date -I)" || true
            while IFS= read -r file; do
              pdf="${file%.*}.pdf"
              echo "Delivering file $pdf"
              gh release upload "$TAG" "$pdf" --clobber
            done <<< "$LATEX_SUCCESSES"
          else
            echo "Not running deployment from unknown source: $GITHUB_REF"
          fi
        fi
# tex files which have a corresponding pdf in assets of a release:
#   hub release show <RELEASENAME> --show-downloads | sed -e 's/.*\///g' | grep -e '.*\.pdf' | sed s/pdf/tex/
# date of release publication
#   hub release show <RELEASENAME> --format "%pI" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}'
# tex files changed since release
#   git log --since="$(hub release show <RELEASENAME> --format "%pr")" --name-only --pretty=format: | sort | uniq
